In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprice.csv")
df

area  bedroom  age   price
0  2000      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [3]:
import math
mid = math.floor(df["bedroom"].median())
df.bedroom.fillna(mid,inplace=True)
df

area  bedroom  age   price
0  2000      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [43]:
rg = linear_model.LinearRegression()
rg.fit(df[["area","bedroom","age"]],df.price)


LinearRegression()

In [5]:
rg.coef_

array([   72.19170404,  6410.31390135, -4523.5426009 ])

In [6]:
rg.intercept_

447125.5605380708

In [7]:
rg.predict([[3000,3,40]])

array([501989.9103139])

In [8]:
72.19170404*3000+6410.31390135*3+-4523.5426009*40+447125.5605380708

501989.9103261208

In [9]:
rg.predict([[2500,5,16]])

array([587279.70852017])

In [26]:
import joblib

In [35]:
jm = joblib.dump(rg,"joblibmodel")

In [37]:
jm = joblib.load("joblibmodel")

In [38]:
import pickle

In [39]:
with open("model","wb") as f:
    pickle.dump(rg,f)

In [40]:
with open("model","rb") as f:
    mb = pickle.load(f)

In [41]:
mb.predict([[2500,5,16]])

array([587279.70852017])

In [42]:
jm.predict([[2500,5,16]])

array([587279.70852017])